name: PSAI Full-Field Daily

permissions:
  contents: write
  pages: write
  id-token: write

on:
  workflow_dispatch:
  schedule:
    - cron: '15 13 * * *'  # daily at 09:15 ET

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML beautifulsoup4 feedgen requests
      - name: Discovery
        run: |
          python scripts/discover.py
          python scripts/merge_candidates.py
      - name: Generate sources
        run: python scripts/generate_sources.py
      - name: Harvest → Log (30d)
        run: python scripts/harvest.py --sources data/sources.yaml --tracker data/PSAI_FullField_Tracker.csv --log data/news_log.json
      - name: Update tracker status
        run: python scripts/update_tracker.py --tracker data/PSAI_FullField_Tracker.csv --log data/news_log.json --out data/PSAI_FullField_Tracker.csv
      - name: Build feeds
        env:
          SITE_URL: ${{ vars.SITE_URL }}
        run: python scripts/build_feed.py --log data/news_log.json --site "${{ env.SITE_URL || 'https://<user>.github.io/<repo>' }}" --json public/feed.json --rss public/rss.xml
      - name: Build sources pages (cards + table)
        run: python scripts/build_sources_pages.py
      - name: Build HTML report
        run: python scripts/build_site.py
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
